1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [41]:
import numpy as np
result = np.fromfunction(lambda i,j: i*j*(9-i)*(9-j)==0, (10,10)).astype(int)
print(result)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [39]:
result = np.fromfunction(lambda i,j: (i+j)%2, (8,8)).astype(int)
print(result)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [37]:
result = np.pad(np.diag(np.arange(1, 5)), ((1,0),(0,1)), mode="constant")
print(result)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [35]:
a = (lambda A: A - A.sum(axis=1)[:, None]/5)(np.random.random((5, 5)))
print(a)
print(a.sum(axis=1)) #эта строчка просто как проверка, что среднее вдоль любой строки 0 (у нас величина порядка 10^-16)#

[[ 0.41607053 -0.13747637 -0.0916404   0.09215802 -0.27911178]
 [ 0.12570363  0.23524842 -0.26818775  0.03690584 -0.12967014]
 [-0.476449    0.21923715 -0.11864762  0.11895051  0.25690896]
 [-0.51132321  0.09874242  0.07715369  0.07851402  0.25691308]
 [ 0.11923064 -0.31294525  0.31133596 -0.2744984   0.15687704]]
[-3.88578059e-16 -2.22044605e-16  1.66533454e-16  0.00000000e+00
  2.22044605e-16]


5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [12]:
x=np.random.random((10, 3))
result = x[np.arange(x.shape[0]), np.argmin(abs(0.5-x), axis=1)]
print(x)
print(result)

[[0.95373969 0.17969638 0.50632528]
 [0.13123891 0.00793491 0.82981689]
 [0.38914799 0.9439477  0.93899028]
 [0.35882938 0.76320284 0.96403656]
 [0.08435236 0.08115875 0.20133578]
 [0.05424439 0.10431949 0.41106138]
 [0.9224521  0.70176029 0.28928839]
 [0.24617015 0.32830129 0.1390888 ]
 [0.18549339 0.8497936  0.49177958]
 [0.35593178 0.97291524 0.02066593]]
[0.50632528 0.82981689 0.38914799 0.35882938 0.20133578 0.41106138
 0.70176029 0.32830129 0.49177958 0.35593178]


6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [31]:
result=(lambda a: a.sum(axis=1)/a.max(axis=0))(np.random.random((6, 6)))
print(result)


[3.2881598  3.22807776 2.4584283  5.08277453 7.92000989 3.53216182]


7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [20]:
result = (lambda x: np.max(x[np.concatenate([[False], x[:-1] == 0])]))(np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]))
print(result)

5


8.Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.



In [23]:
x=np.ones(10)
(lambda i: np.add.at(x, i, 1))(np.array([0, 1, 2, 3, 5, 5, 5, 8]))
print(x.astype(int))

[2 2 2 2 1 4 1 1 2 1]


9. Задайте два массива a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [33]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])
result=b[np.argmin(abs(a[:, :, np.newaxis]-b), axis=2)]
print(result)

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


10. Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [29]:
result=np.convolve(np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]), [1/3, 1/3, 1/3], mode='valid')
print(result)

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]
